config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "user/registrations"}

    root to: 'pages#index'

    # Pages
    get '/donation', to: 'pages#donation', as: 'donation'
    post '/webhook', to: 'pages#webhook'
    get '/about', to: 'pages#about', as: 'about'

    # Pets
    get '/pets', to: 'pets#index', as: 'pets'
    get '/pets/new', to: 'pets#new', as: 'new_pet'
    post '/pets', to: 'pets#create'
    get '/pets/user_pets', to: 'pets#index_user_pets', as: 'user_pets'
    get '/pets/:id', to: 'pets#show', as: 'pet'
    put '/pets/:id', to: 'pets#update'
    patch '/pets/:id', to: 'pets#update'
    delete '/pets/:id', to: 'pets#destroy', as: 'delete_pet'
    get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
    
    # Foster Requests
    # get '/pets/:id', to: 'pets#show', as: 'foster_requests'
    get '/pets/:id/new_foster_request', to: 'foster_requests#new', as: 'new_foster_request'
    post '/pets/:id/new_foster_request', to: 'foster_requests#create'
    get '/pets/:id/end_foster_request', to: 'foster_requests#end_fostering', as: 'end_foster_request'
    post '/pets/:id/end_foster_request', to: 'foster_requests#terminate'
    get '/pets/:id/foster_requests', to: 'foster_requests#show_per_pet', as: 'foster_requests_per_pet'
    get '/foster_requests', to: 'foster_requests#index', as: 'foster_requests'
    get '/foster_requests/:id', to: 'foster_requests#show', as: 'show_foster_request'
    put '/foster_requests/:id', to: 'foster_requests#approve'
    patch '/foster_requests/:id', to: 'foster_requests#approve', as: 'approve_foster_request'

    # Contact
    get '/contacts', to: 'contacts#new', as: 'new_contact'
    post '/contacts', to: 'contacts#create'
end

app/models/foster_request.rb
class FosterRequest < ApplicationRecord
    # foster request belongs to the user and also to the pet
    belongs_to :guardian, class_name: 'User'
    belongs_to :pet

    # enum to easily manage the request status in database
    enum status: [:reviewed, :declined, :approved, :terminated]
end

app/controllers/foster_requests_controller.rb
class FosterRequestsController < ApplicationController
    # foster request can only be sent once the user is signed in
    before_action :authenticate_user!
    # check the user's account type
    before_action :authorize_user, only: [:new, :create, :show, :approve, :show_per_pet]
    # retrieve foster request details (FosterRequest model object) when reviewing
    before_action :get_foster_request, only: [:show, :approve]
    # retrieve pet details (Pet model object)
    before_action :get_pet, only: [:new, :create, :end_fostering, :terminate, :show_per_pet]

    def index
    end

    def new
        # create new foster request model on page load
        @foster_request = FosterRequest.new
    end

    def create
        # retrieve pet object based on passed over id
        pet = Pet.find(params[:id])
        # if the pet is already fostered and the current user is not that person
        # (in this case we check whether the pet is already fostered or not by checking if the pet already has a guardian or not
        # as guardian column can be left null when the pet is not fostered)
        if pet.guardian && pet.guardian != current_user
            # alert the message
            flash[:alert] = "#{@pet.name} is already fostered!"

            # return to that pet's page
            redirect_to pet_path(params[:id])

            return
        end
        
        # retrieve foster request object based on the pet object that is retrieved with the id passed and current user object
        # the .last is to retrieve the very last foster request from the database since the .last gives the most recent foster request 
        # as the user might have fostered this pet in the past and might be re-fostering that specific pet I am using .last
        foster_request = FosterRequest.where(pet: pet, guardian: current_user).last
        # if the foster request already exists and is still being reviewed by the shelter
        if foster_request && foster_request.reviewed?
            # alert message
            flash[:alert] = "You have already subbmitted a foster request for #{@pet.name}!"

            # return to the pet's page
            redirect_to pet_path(params[:id])

            return
        end

        # now create the new foster request based on pet and current user objects as well as the comment passed via the form
        @foster_request = FosterRequest.new(pet: pet, guardian: current_user, comment: params[:comment])
        # if the foster request is successfully saved
        if @foster_request.save
            # return to the pet's page with message
            redirect_to pet_path(params[:id]), notice: "You have successsfully submitted a foster request!"

            return
        else
            # if fails, alert the message
            flash[:alert] = "Something went wrong!"

            # then return to the pet's page
            redirect_to pet_path(params[:id])

            return
        end
    end

    def show
    end

    def approve
        # retrieve the all foster requests where the pet is the pet of the foster request that is currently being reviewed
        # and status is where the requests those are waiting to be reviewed by the shelter representative
        foster_requests = FosterRequest.where(pet: @foster_request.pet, status: :reviewed)

        # loop through every single foster requests retrieved above
        foster_requests.each_with_index do |foster_request, index|
            # if the request is equal to what the shelter representative is currently reviewing
            if @foster_request == foster_request
                # approve the guardian's request
                foster_request.approved!

                # update the related pet's guardian column then save
                foster_request.pet.update(guardian: foster_request.guardian)
                foster_request.pet.save
            else
                # for all other foster requests set the status to declined
                foster_request.declined!
            end

            # when reach to the very last request
            if foster_requests[index] == foster_requests.last
                # alert the message and return to the pet's page
                redirect_to pet_path(foster_request.pet.id), notice: "You have successsfully selected guardian for #{@foster_request.pet.name}!"

                return
            end
        end
    end

    def end_fostering
    end

    def terminate
        # retrieve foster request object based on the pet object that is retrieved with the id passed and current user object
        # the .last is to retrieve the very last foster request from the database since the .last gives the most recent foster request 
        # as the user might have fostered this pet in the past and might be re-fostering that specific pet I am using .last
        foster_request = FosterRequest.where(pet: @pet, guardian: current_user).last
        
        # create a review data based on the comment
        # obviously the reviewer is the current user, the guardian
        @pet.reviews.create(reviewer: current_user, comment: params[:comment])
        
        # set the status of foster request to terminated
        foster_request.terminated!
        # empty out the pet's guardian
        foster_request.pet.guardian = nil
        # if the data is successfully saved
        if foster_request.pet.save
            # alert the message and return to the pet's page
            redirect_to @pet, notice: "Thank you for taking a good care of #{@pet.name}!"

            return
        else
            # otherwise alert and return to the pet's page
            flash[:alert] = "Something went wrong!"

            redirect_to @pet

            return
        end
    end

    def show_per_pet
        # the authentication process to prevent a random person from accessing foster requests
        # only the pet's shelter representatives can review foster requests
        if @pet.shelter.id != current_user.id
            flash[:alert] = "#{@pet.name} does not belong to your shelter!"

            redirect_to pets_path

            return
        end

        # retrieve all foster requests for the specific pet where the requests needs to be reviewed
        @foster_requests = @pet.foster_requests.where(status: :reviewed).all
    end

    private
        def get_foster_request
            # retrieve foster request based on passed id value
            @foster_request = FosterRequest.find(params[:id])
        end

        def get_pet
            # retrieve pet based on passed id value
            @pet = Pet.find(params[:id])
        end

        def authorize_user
            # check whether the current user type is shelter or guardian
            if current_user.shelter?
                authorize_shelter
            else
                authorize_guardian
            end
        end

        def authorize_shelter
            # do not allow shelter representatives create foster request
            action = params[:action]
            if action == "new" || action == "create"
                flash[:alert] = "Only guardians can access this page!"

                redirect_to foster_requests_path

                return
            end
        end

        def authorize_guardian
            # do not allow guardians to review foster requests nor permit them to approve the request
            action = params[:action]
            if action == "approve" || action == "show_per_pet"
                flash[:alert] = "Only shelter representatives can access this page!"

                redirect_to foster_requests_path

                return
            else
                
            end
        end

        # security process to only permit comment data
        def permit_params
            return params.require(:pet).permit(:comment)
        end
end

app/helpers/foster_requests_helper.rb
module FosterRequestsHelper
end

app/views/foster_requests/end_fostering.html.erb
<section class="container end-fostering-section">
    <div class="d-flex shadow bg-white rounded end-fostering-block">
        <div class="w-50 end-fostering-image-container">
            <%# check if the retrieved pet has its picture attached %>
            <%# if it does, display that image %>
            <%# otherwise display the default image %>
            <%= image_tag @pet.picture.attached? ? @pet.picture : 'cozynest_image_default.jpg', class: "w-100 h-auto end-fostering-image" %>
        </div>
        <div class="w-50 end-fostering-details-container">
            <%= form_with url: end_foster_request_path, method: :post, html: {class: "w-100"} do |form| %>
                <div class="pb-2">
                    <small class="font-weight-bold">Name:</small>
                    <br>
                    <%= @pet.name %>
                </div>
                <div class="pb-2">
                    <small class="font-weight-bold">Comment:</small>
                    <br>
                    <%= form.text_area :comment, rows: 8, cols: 40, required: true, class: "form-control" %>
                </div>
                <div>
                    <%# double check if the user really wants to terminate foster %>
                    <%= form.button "Submit", data: {confirm: "Are you sure?"}, class: "btn btn-primary w-100" %>
                </div>
            <% end %>
        </div>
    </div>
    <%= link_to "Back", @pet %>
</section>

app/views/foster_requests/index.html.erb
<% current_user.pets.each do |pet| %>
    <% if pet.foster_requests.count > 0 %>
        <h1>
            <%= link_to pet.name, foster_requests_per_pet(pet.id) %>
        </h1>
        <% pet.foster_requests.each do |foster_request| %>
            <div>
                <div>
                    <%= foster_request.guardian.username %>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/foster_requests/new.html.erb
<section class="container foster-request-section">
    <div class="d-flex shadow bg-white rounded foster-request-block">
        <div class="w-50 foster-request-image-container">
            <%# check if the retrieved pet has its picture attached %>
            <%# if it does, display that image %>
            <%# otherwise display the default image %>
            <%= image_tag @pet.picture.attached? ? @pet.picture : 'cozynest_image_default.jpg', class: "w-100 h-auto foster-request-image" %>
        </div>
        <div class="w-50 foster-request-form-container">
            <%= form_with url: new_foster_request_path, method: :post, html: {class: "w-100"} do |form| %>
                <div class="pb-2">
                    <small class="font-weight-bold">Name:</small>
                    <br>
                    <%= @pet.name %>
                </div>
                <div class="pb-2 flex-grow-1">
                    <small class="font-weight-bold">Comment:</small>
                    <br>
                    <%= form.text_area :comment, rows: 4, cols: 40, class: "form-control" %>
                </div>
                <div class="pb-2">
                    <%# double check if the user has properly entered comments %>
                    <%= form.button "Submit", data: {confirm: "Once you submit you will not be able to make modifications. Are you sure?"}, class: "btn btn-primary w-100" %>
                </div>
            <% end %>
        </div>
    </div>
</section>
<%= link_to "Back", @pet %>

app/views/foster_requests/show.html.erb
<section class="container foster-request-review-section">
    <div class="d-flex shadow bg-white rounded foster-request-review-block">
        <div class="w-50 foster-request-review-image-container">
            <%# check if the retrieved foster request's pet has its picture attached %>
            <%# if it does, display that image %>
            <%# otherwise display the default image %>
            <%= image_tag @foster_request.pet.picture.attached? ? @foster_request.pet.picture : 'cozynest_image_default.jpg', class: "w-100 h-auto foster-request-review-image" %>
        </div>
        <div class="w-50 foster-request-review-details-container">
            <%= form_with url: approve_foster_request_path, method: :patch, html: {class: "w-100"} do |form| %>
                <div class="pb-2">
                    <small class="font-weight-bold">Name:</small>
                    <br>
                    <%= @foster_request.guardian.username %>
                </div>
                <div class="pb-2">
                    <small class="font-weight-bold">Comment:</small>
                    <br>
                    <%= @foster_request.comment %>
                </div>
                <%# render the accept button only if the pet of the foster request that is being reviewed does not have guardian %>
                <% if not @foster_request.pet.guardian %>
                    <div class="pb-2">
                        <%= form.button "Accept", data: {confirm: "Are you sure?"}, class: "btn btn-primary w-100" %>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
    <%= link_to "Back", foster_requests_per_pet_path(@foster_request.pet_id) %>
</section>

app/views/foster_requests/show_per_pet.html.erb
<section class="container requests-per-pet-section">
    <div class="d-flex shadow bg-white rounded requests-per-pet-block">
        <div class="w-50 requests-per-pet-image-container">
            <%# check if the retrieved pet has its picture attached %>
            <%# if it does, display that image %>
            <%# otherwise display the default image %>
            <%= image_tag @pet.picture.attached? ? @pet.picture : 'cozynest_image_default.jpg', class: "w-100 h-auto requests-per-pet-image" %>
        </div>
        <div class="w-50 d-flex flex-column requests-per-pet-details-container">
            <%# only render foster requests if they really exist %>
            <% if @foster_requests.count > 0 %>
                <% @foster_requests.each do |foster_request| %>
                    <div class="mb-2 w-100 border shadow bg-white rounded">
                        <div class="p-2 d-flex flex-column">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <small class="font-weight-bold">Name:</small>
                                    <br>
                                    <%= foster_request.guardian.username %>
                                </div>
                                <div>
                                    <small class="font-weight-bold">Date:</small>
                                    <br>
                                    <%= format_time(foster_request.created_at) %>
                                </div>
                            </div>
                            <div class="align-self-end">
                                <small>
                                    <%# link to each request detail's page %>
                                    <%= link_to "Show details", show_foster_request_path(foster_request.id), class: "btn btn-primary w-100" %>
                                </small>
                            </div>
                        </div>
                    </div>
                <% end %>
            <%# if there are no foster requests, yet, just print plain text %>
            <% else %>
                <div class="mb-2 w-100 d-flex justify-content-center align-items-center flex-grow-1">
                    <h3>No requests have been made yet!</h3>
                </div>
            <% end %>
        </div>
    </div>
    <%= link_to "Back", @pet %>
</section>