config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "user/registrations"}

    root to: 'pages#index'

    # Pages
    get '/donation', to: 'pages#donation', as: 'donation'
    post '/webhook', to: 'pages#webhook'
    get '/about', to: 'pages#about', as: 'about'

    # Pets
    get '/pets', to: 'pets#index', as: 'pets'
    get '/pets/new', to: 'pets#new', as: 'new_pet'
    post '/pets', to: 'pets#create'
    get '/pets/user_pets', to: 'pets#index_user_pets', as: 'user_pets'
    get '/pets/:id', to: 'pets#show', as: 'pet'
    put '/pets/:id', to: 'pets#update'
    patch '/pets/:id', to: 'pets#update'
    delete '/pets/:id', to: 'pets#destroy', as: 'delete_pet'
    get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
    
    # Foster Requests
    # get '/pets/:id', to: 'pets#show', as: 'foster_requests'
    get '/pets/:id/new_foster_request', to: 'foster_requests#new', as: 'new_foster_request'
    post '/pets/:id/new_foster_request', to: 'foster_requests#create'
    get '/pets/:id/end_foster_request', to: 'foster_requests#end_fostering', as: 'end_foster_request'
    post '/pets/:id/end_foster_request', to: 'foster_requests#terminate'
    get '/pets/:id/foster_requests', to: 'foster_requests#show_per_pet', as: 'foster_requests_per_pet'
    get '/foster_requests', to: 'foster_requests#index', as: 'foster_requests'
    get '/foster_requests/:id', to: 'foster_requests#show', as: 'show_foster_request'
    put '/foster_requests/:id', to: 'foster_requests#approve'
    patch '/foster_requests/:id', to: 'foster_requests#approve', as: 'approve_foster_request'

    # Contact
    get '/contacts', to: 'contacts#new', as: 'new_contact'
    post '/contacts', to: 'contacts#create'
end

app/models/pet.rb
class Pet < ApplicationRecord
    # pet object belongs to pet category
    belongs_to :category, class_name: 'PetCategory'
    
    # pet object also belongs to shelter and guardian
    # shelter column must exist, but guardian can be left null
    belongs_to :shelter, class_name: 'User'
    belongs_to :guardian, class_name: 'User', optional: true
    
    # pet object can have many foster requests
    # if the pet object is destroyed from the database, all foster requests must be gone as well
    has_many :foster_requests, dependent: :destroy
    
    # pet object can have many reviews
    has_many :reviews, as: :reviewable
    
    # the name and description column of pet object cannot be left blank
    validates :name, presence: true, allow_blank: false
    validates :description, presence: true, allow_blank: false
    
    # each pet object can have related image file which is stored in AWS
    has_one_attached :picture
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    # allow guests to view the all pets registered and each pet's details
    before_action :authenticate_user!, except: [:index, :show]
    # retrieve pet details for CRUD
    before_action :get_pet, only: [:show, :edit, :update, :destroy]
    # authorize user for CRUD
    before_action :authorize_user, only: [:new, :create, :edit, :update, :destroy]
    # retrieve all categories on create and update
    before_action :get_categories, only: [:new, :edit]

    def index
        # retrieve all pet data from the database
        @pets = Pet.all
    end

    def show
    end

    def new
        # create new pet model on page load
        @pet = Pet.new
    end

    def create
        # create new pet object, but also append shelter details
        @pet = Pet.new(permit_params.merge(:shelter => current_user))
        # when successfully saved
        if @pet.save
            # return to pet's page and alert
            redirect_to @pet, notice: "Pet has been successfully added!"
        else
            # retrieve pet categories again
            get_categories
            
            # render the page again so the user could restart from the scratch
            render "new", notice: "Something went wrong!"

            return
        end
    end

    def edit
    end

    def update
        # update pet details and again, append shelter details
        # this might be redundant, but is done for extra safety
        @pet.update(permit_params.merge(:shelter => current_user))
        # when successfully saved
        if @pet.save
            # return to the pet's page and alert
            redirect_to @pet, notice: "Pet has been successfully added!"
        else
            # otherwise retrieve pet categories again
            get_categories
            
            # render the page again
            render "edit", notice: "Something went wrong!"

            return
        end
    end

    def destroy
        # delete pet object from the database
        @pet.destroy

        # return to the pets page and alert
        redirect_to pets_path, notice: "Successfully deleted!"

        return
    end

    def show_user_pets
    end

    private
        def get_categories
            # retrieve all categories objects
            @categories = PetCategory.all
        end

        def get_pet
            # retrieve pet with the passed over id value
            @pet = Pet.find(params[:id])
        end

        def authorize_user
            # check whether the current user type is shelter or guardian
            if current_user.shelter?
                authorize_shelter
            else
                authorize_guardian
            end
        end

        def authorize_shelter
            # only allow shelter representatives to CRUD the pet
            # however, do not allow the current user to UD the pet data, if the current user is not the pet's shelter manager
            action = params[:action]
            if action == "new" || action == "create"
                return
            elsif action == "edit" || action == "update" || action == "destroy"
                if @pet.shelter.id != current_user.id
                    flash[:alert] = "#{@pet.name} does not belong to your shelter!"

                    redirect_to pets_path

                    return
                end
            else
                flash[:alert] = "Only guardians can access this page!"

                redirect_to pets_path

                return
            end
        end

        def authorize_guardian
            # obviously we don't want guardians to CRUD pet object
            flash[:alert] = "Only shelter representatives can access this page!"

            redirect_to pets_path

            return
        end

        # security process to only permit name, category, description and picture of the pet
        def permit_params
            return params.require(:pet).permit(:name, :category_id, :description, :picture)
        end
end

app/helpers/pets_helper.rb
module PetsHelper
    # to format category for drop down menu
    def format_category(category)
        return category.capitalize
    end
end

app/views/pets/_form.html.erb
<%# a form that is shared via new and edit page %>
<div class="d-flex shadow bg-white rounded pet-manage-block">
    <div class="w-50 pet-manage-image-container">
        <%= image_tag "cozynest_pet_manage.jpg", class: "w-100 h-auto pet-manage-image" %>
    </div>
    <div class="w-50 pet-manage-form-container">
        <%= form_with model: @pet, local: true, html: {class: "w-100"} do |form| %>
            <%# print all errors %>
            <% if @pet.errors.any? %>
                <div>
                    <h2>
                        <%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:
                    </h2>
                    <ul>
                        <% @pet.errors.each do |error| %>
                            <li>
                                <%= error.full_message %>
                            </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="form-group">
                <small class="font-weight-bold"><%= form.label :name %></small>
                <br />
                <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <small class="font-weight-bold"><%= form.label :category_id %></small>
                <br />
                <%# fill the dropdown menu with the category values retrieved %>
                <%= form.select :category_id, @categories.map {|category| [format_category(category.name), category.id]}, {}, {class: "form-control form-select"} %>
            </div>
            <div class="form-group">
                <small class="font-weight-bold"><%= form.label :description %></small>
                <br />
                <%= form.text_area :description, rows: 4, cols: 40, class: "form-control" %>
            </div>
            <div class="form-group">
                <small class="font-weight-bold"><%= form.label :picture %></small>
                <br />
                <%= form.file_field :picture, accept: "image/png, image/jpg, image/jpeg" %>
            </div>
            <br />
            <div class="form-group">
                <%= form.submit class: "btn btn-primary w-100" %>
            </div>
            
            <div>
                <% if current_page?(:controller => 'pets', :action => 'new') %>
                    <%= link_to "Back", root_url, style: "color: black; text-decoration: none;" %>
                <% elsif current_page?(:controller => 'pets', :action => 'edit') %>
                    <%= link_to "Back", pet_path(@pet.id), style: "color: black; text-decoration: none;" %>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/pets/_pets.html.erb
<%# a simple card that is shared via pet's index page as well as the user specific pets page %>
<div class="container">
    <div class="row">
        <% pets.each do |pet| %>
            <div class="col-md-4">
                <div class="card click-col bg-cover text-white pets-card pets-card-bg" style="background-image: url(<%= pet.picture.attached? ? pet.picture.url : image_url('cozynest_image_default.jpg') %>);">
                    <div class="card-img-overlay d-flex flex-column">
                        <div class="card-body">
                            <small class="pets-card-category mb-2">
                                <%= format_category(pet.category.name) %>
                            </small>
                            <h4 class="card-title mt-0">
                                <%= link_to pet.name, pet_path(pet.id) %>
                            </h4>
                            <small>
                                <%= format_time(pet.created_at) %>
                            </small>
                        </div>
                        <div class="card-footer pets-card-footer">
                            <div class="media">
                                <div class="media-body">
                                    <h6 class="my-0 text-white d-block">
                                        <%= pet.shelter.username %>
                                    </h6>
                                    <small>
                                        <%= pet.shelter.email %>
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/pets/edit.html.erb
<section class="container pet-manage-section">
    <%= render 'form' %>
</section>

app/views/pets/index.html.erb
<section class="pets-section">
    <h2 class="d-flex justify-content-center">
        Pets
    </h2>
    <%= render 'pets', pets: @pets %>
</section>

app/views/pets/index_user_pets.html.erb
<section class="pets-section">
    <h2 class="d-flex justify-content-center">
        <%= current_user.username%>'s Pet List
    </h2>
    <%= render 'pets', pets: current_user.pets %>
</section>

app/views/pets/new.html.erb
<section class="container pet-manage-section">
    <%= render 'form' %>
</section>

app/views/pets/new_foster_request.html.erb
<%= form_with url: new_foster_request_path, method: :post do |form| %>
    <div class="field">
        <%= form.label :pet_name, "Pet name: #{@pet.name}" %>
    </div>

    <div class="field">
        <%= form.button "Submit Foster Request" %>
    </div>

    <div class="field">
        <%= link_to "Back", pet_path(@pet.id) %>
    </div>
<% end %>

app/views/pets/show.html.erb
<section class="container pet-show-section">
    <div class="d-flex shadow bg-white rounded pet-show-block">
        <div class="w-50 pet-show-image-container">
            <%# check if the retrieved pet has its picture attached %>
            <%# if it does, display that image %>
            <%# otherwise display the default image %>
            <%= image_tag @pet.picture.attached? ? @pet.picture : 'cozynest_image_default.jpg', class: "w-100 h-auto pet-show-image", alt: @pet.name %>
        </div>
        <div class="w-50 pet-show-details-container">
            <div class="pb-2">
                <small class="font-weight-bold">Name:</small>
                <br>
                <%= @pet.name %>
            </div>
            <div class="pb-2">
                <small class="font-weight-bold">Category:</small>
                <br>
                <%= format_category(@pet.category.name) %>
            </div>
            <div class="pb-2 flex-grow-1" style="text-overflow: ellipsis;">
                <small class="font-weight-bold">Description:</small>
                <br>
                <%= @pet.description %>
            </div>
            <div class="pb-2 d-flex justify-content-between">
                <div>
                    <small class="font-weight-bold">Shelter:</small>
                    <br>
                    <%= @pet.shelter.username %>
                </div>
                <% if current_user && current_user.shelter? && current_user == @pet.shelter %>
                    <% if @pet.guardian %>
                        <div>
                            <small class="font-weight-bold">Fosterer:</small>
                            <br>
                            <%= @pet.guardian.username %>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <% if current_user %>
                <%# if the current user is a shelter representative and is the pet's shelter manager %>
                <% if current_user.shelter? && current_user == @pet.shelter %>
                    <div class="d-flex justify-content-end pb-1">
                        <%# if the pet is still not fostered %>
                        <% if not @pet.guardian %>
                            <div class="pr-1">
                                <%# put the review request button %>
                                <%= link_to "Review requests", foster_requests_per_pet_path(@pet.id), class: "btn btn-primary" %>
                            </div>
                        <% end %>
                        <div class=<%= "pr-1" if not @pet.guardian %>>
                            <%= link_to "Edit", edit_pet_path(@pet.id), class: "btn btn-warning" %>
                        </div>
                        <%# if the pet is still not fostered %>
                        <% if not @pet.guardian %>
                            <div>
                                <%# put the delete pet button %>
                                <%= link_to "Delete", @pet, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
                            </div>
                        <% end %>
                    </div>
                <%# if the current user is a guardian %>
                <% elsif current_user.guardian? %>
                    <div>
                        <%# if the pet is not fostered yet %>
                        <% if not @pet.guardian %>
                            <%# put the foster button %>
                            <%= link_to "Foster", new_foster_request_path(@pet.id), class: "btn btn-primary w-100" %>
                        <%# if the current user is a guardian of the pet %>
                        <% elsif current_user == @pet.guardian %>
                            <%# put the end fostering button %>
                            <%= link_to "End fostering", end_foster_request_path(@pet.id), class: "btn btn-danger w-100" %>
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
    <br>
    <div class="p-3 shadow bg-white rounded d-flex flex-column">
        <small class="mb-2 font-weight-bold">Comments:</small>
        <%# render all the existing comments for the pet %>
        <% if @pet.reviews.count > 0 %>
            <% @pet.reviews.each do |review| %>
                <div>
                    <small class="font-weight-bold text-info">
                        <%= "#{review.reviewer.username} (#{format_time(review.created_at)}):" %>
                    </small>
                    <br>
                    <%= review.comment != "" ? review.comment : "None" %>
                </div>
            <% end %>
        <% else %>
            No comments exists!
        <% end %>
    </div>
    <%= link_to "Back", @pet %>
</section>

app/views/pets/show_user_pets.html.erb
<section class="wrapper">
    <h2 class="d-flex justify-content-center">
        <%= current_user.username%>'s Pet List
    </h2>
    <%= render 'pets', pets: current_user.pets %>
</section>