config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => {:registrations => "user/registrations"}

    root to: 'pages#index'

    # Pages
    get '/donation', to: 'pages#donation', as: 'donation'
    post '/webhook', to: 'pages#webhook'
    get '/about', to: 'pages#about', as: 'about'

    # Pets
    get '/pets', to: 'pets#index', as: 'pets'
    get '/pets/new', to: 'pets#new', as: 'new_pet'
    post '/pets', to: 'pets#create'
    get '/pets/user_pets', to: 'pets#index_user_pets', as: 'user_pets'
    get '/pets/:id', to: 'pets#show', as: 'pet'
    put '/pets/:id', to: 'pets#update'
    patch '/pets/:id', to: 'pets#update'
    delete '/pets/:id', to: 'pets#destroy', as: 'delete_pet'
    get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
    
    # Foster Requests
    # get '/pets/:id', to: 'pets#show', as: 'foster_requests'
    get '/pets/:id/new_foster_request', to: 'foster_requests#new', as: 'new_foster_request'
    post '/pets/:id/new_foster_request', to: 'foster_requests#create'
    get '/pets/:id/end_foster_request', to: 'foster_requests#end_fostering', as: 'end_foster_request'
    post '/pets/:id/end_foster_request', to: 'foster_requests#terminate'
    get '/pets/:id/foster_requests', to: 'foster_requests#show_per_pet', as: 'foster_requests_per_pet'
    get '/foster_requests', to: 'foster_requests#index', as: 'foster_requests'
    get '/foster_requests/:id', to: 'foster_requests#show', as: 'show_foster_request'
    put '/foster_requests/:id', to: 'foster_requests#approve'
    patch '/foster_requests/:id', to: 'foster_requests#approve', as: 'approve_foster_request'

    # Contact
    get '/contacts', to: 'contacts#new', as: 'new_contact'
    post '/contacts', to: 'contacts#create'
end

app/views/shared/_footer.html.erb
<footer class="page-footer font-small">
    <div class="container">
        <div class="row text-center d-flex justify-content-center align-contents-center pt-5 mb-3">
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <%= link_to "Home", root_url, class: "color-white" %>
                </h6>
            </div>
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <%= link_to "About", about_path, class: "color-white" %>
                </h6>
            </div>
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <%= link_to "Contact", new_contact_path, class: "color-white" %>
                </h6>
            </div>
        </div>
    </div>
    <hr class="rgba-white-light" style="margin: 0 15%;">
    <div class="footer-copyright text-center py-3 color-grey" style="background-color: rgba(0, 0, 0, 0.3);">
        Copyright&#169; <%= Time.new.year %>. <%= link_to "Cozynest", "https://cozynest.herokuapp.com/", class: "color-white" %>. All rights reserved.
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
    <div class="col-4 align-items-center">
        <%= link_to "Cozynest", root_url, class: "navbar-brand" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarToggler">
        <ul class="navbar-nav col-4 d-flex justify-content-end">
            <li class="nav-item">
                <%= link_to "Home", root_url, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Pets", pets_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Donation", donation_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle">
                        <%= current_user.username %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Manage pets", user_pets_path, class: "dropdown-item" %>
                        <% if current_user.shelter? %>
                            <%= link_to "Register pet", new_pet_path, class: "dropdown-item" %>
                        <% end %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
                    </div>
                </li>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
            <% end %>
        </ul>
    </div>
</nav>